# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore & Build Project
  inputs:
    command: build
    projects: '**/*App/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
    zipAfterPublish: true

- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: Publish Simple Function Artifacts
  inputs:
    PathtoPublish: 'src/SimpleAzureFunctionApp/bin/Release/netstandard2.0'
    artifactName: 'SimpleFunctionApp' 
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: Publish Cold Start Demo Function Artifacts
  inputs:
    PathtoPublish: 'src/ColdStartDemoFunctionApp/bin/Release/netstandard2.0' 
    artifactName: 'ColdStartDemoFunctionApp' 
    publishLocation: 'Container'
